MultipassHostel/Multipass.Web/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Multipass.Web.Models
{
    // Form Model
    public class Employee
    {
        [Display(Name = "Emp ID")]
        [Required]
        public int Id { get; set; }

        [Display(Name = "Full Name")]
        [Required]
        public string FullName { get; set; }

        [Display(Name = "Salary")]
        [Required]
        public int Salary { get; set; }

        [Display(Name = "Position")]
        [Required]
        public string Position { get; set; }

        [Display(Name = "School")]
        [Required]
        public string School { get; set; }

        [Display(Name = "Age")]
        [Required]
        public int Age { get; set; }
    }
}

MultipassHostel/Multipass.Web/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Multipass.Web.Models
{
    public class EmployeeViewModel
    {

        public Employee EditedEmployee { get; set; }

        public List<Employee> ListAllEmployees { get; set; }
    }
}

MultipassHostel/Multipass.Web/Controllers/EmployeesController.cs
using AutoMapper;
using Multipass.Logic;
using Multipass.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Multipass.Web.Controllers
{
    public class EmployeesController : Controller
    {
        ILogic logic;
        IMapper mapper;
        EmployeeViewModel vm;

        public EmployeesController()
        {
            logic = new BusinessLogic();

            mapper = MapperFactory.CreateMapper();
            vm = new EmployeeViewModel();
            vm.EditedEmployee = new Employee();

            var employees = logic.getAllEmployees();
            vm.ListAllEmployees = mapper.Map<IList<Data.employee>, List<Models.Employee>>(employees);
        }

        private Employee GetEmployeeModel(int id)
        {
            Multipass.Data.employee emp = logic.getEmployee(id);
            return mapper.Map<Data.employee, Models.Employee>(emp);
        }

        // GET: Employees
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("EmployeeIndex", vm);
        }

        // GET: Employees/Details/5
        public ActionResult Details(int id)
        {
            return View("EmployeesDetails",GetEmployeeModel(id));
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedEmployee = GetEmployeeModel(id);
            return View("EmployeeIndex", vm);
        }

        // POST: Employees/Edit/5
        [HttpPost]
        public ActionResult Edit(Employee emp, string editAction)
        {
            try
            {
                if (ModelState.IsValid && emp != null)
                {
                    TempData["editResult"] = "Edit oks";
                    if (editAction == "AddNew")
                    {
                        logic.createEmployee(emp.Id, emp.FullName, emp.Salary, emp.Position, emp.School, emp.Age);
                    }
                    else
                    {
                        //bool success = logic.modifyEmployee --> ez a metodus meg nincs a logicban, csak egyenkenti parameteresen
                        bool success = false;
                        if (!success) TempData["editResult"] = "Edit failed.";
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewData["editAction"] = "Edit";
                    vm.EditedEmployee = emp;
                    return View("EmployeeIndex", emp);
                }

            }
            catch
            {
                return View();
            }
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int id)
        {
            TempData["editResult"] = "Delete failed.";
            if (logic.deleteEmployee(id)) TempData["editResult"] = "Delete successfull";
            return RedirectToAction(nameof(Index));
        }
        
    }
}

MultipassHostel/Multipass.Web/Views/Employees/EmployeeIndex.cshtml
@model Multipass.Web.Models.EmployeeViewModel

@{
    ViewBag.Title = "Crud Index";
}

<h2>EmployeeIndex</h2>


<p style="color:red">
    @TempData["editResult"]
</p>

@Html.Partial("EmployeesEdit", Model.EditedEmployee)

@Html.Partial("EmployeesList", Model.ListAllEmployees)

MultipassHostel/Multipass.Web/Views/Employees/EmployeesDetails.cshtml
@model Multipass.Web.Models.Employee

@{
    ViewBag.Title = "EmployeeDetails";
}

<h2>Datasheet of one employee</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.FullName)</td>
        <td>@Html.DisplayFor(m => m.FullName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Salary)</td>
        <td>@Html.DisplayFor(m => m.Salary)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Position)</td>
        <td>@Html.DisplayFor(m => m.Position)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.School)</td>
        <td>@Html.DisplayFor(m => m.School)</td>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Age)</td>
        <td>@Html.DisplayFor(m => m.Age)</td>
    </tr>
    </tr>
</table>

MultipassHostel/Multipass.Web/Views/Employees/EmployeesEdit.cshtml
@model Multipass.Web.Models.Employee

@{
    /**/

    ViewBag.Title = "EmployeesEdit";
}

<h2>EmployeeEdit</h2>

@using (Html.BeginForm("Edit", "Employees"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.FullName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.FullName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Position)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Position)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Salary)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Salary)</div>

    <div class="editor-label">@Html.LabelFor(m => m.School)</div>
    <div class="editor-field">@Html.EditorFor(m => m.School)</div>

    <input type="submit" value="SEND" />
}

MultipassHostel/Multipass.Web/Views/Employees/EmployeesList.cshtml
@model IEnumerable<Multipass.Web.Models.Employee>

@{
    ViewBag.Title = "EmployeesList";
}

<h2>EmployeesList</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!!!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().FullName)</th>
            <th>@Html.DisplayNameFor(m => m.First().Position)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.FullName)</td>
                <td>@Html.DisplayFor(m => item.Position)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Delete", new { id = item.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>
            </tr>
        }
    </table>
}